version: '3.7'

services:
  octoprint:
    restart: unless-stopped
    container_name: octoprint
    image: "octoprint/octoprint"
    devices:
#      - /dev/ttyACM0:/dev/ttyACM0
      - /dev/video3:/dev/video0
    volumes:
      - ./:/octoprint
    ports:
      - "5000:80"
    environment:
      - ENABLE_MJPG_STREAMER=true
#      - CAMERA_DEV="/dev/video0"
      

#    mem_limit: 23m
